# Generated by Django 4.2.5 on 2023-11-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artistsapp', '0004_alter_album_artist_alter_artist_name_alter_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistsapp.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
